version: '3.8'

services:
  dashboard-container:
    image: postgres
    container_name: dashboard-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dashboard_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dashboard_data:
    name: dashboard_data
